import type { AuditAction, AuditActorRole } from "@/domain/audit";
import type { LokasiMitraStatus } from "@/domain/lokasi";
import { staffRoleLabels } from "./staff-role-labels";

/** How each Lokasi Mitra status is named on screen (CONTEXT.md). */
export const lokasiStatusLabels: Record<LokasiMitraStatus, string> = {
  belum_tayang: "Belum Tayang",
  terverifikasi: "Terverifikasi",
  ditangguhkan: "Ditangguhkan",
  berhenti: "Berhenti",
};

/** What an Entri Audit's action is called in a Lokasi's Audit Log. */
export const auditActionLabels: Record<AuditAction, string> = {
  "staf.seed_admin_platform": "Admin Platform pertama dibuat",
  "staf.undang": "Undangan Staf dikirim",
  "staf.peran_diberikan": "Peran staf diterima",
  "staf.nonaktifkan": "Akun Staf dinonaktifkan",
  "staf.lepas_admin_lokasi": "Admin Lokasi dilepas",
  "akun.pemulihan": "Pemulihan Akun",
  "akun.ubah_telepon": "Ubah nomor telepon",
  "akun.totp_daftar": "Authenticator didaftarkan",
  "akun.totp_reset": "Authenticator direset",
  "katalog_lama.impor": "Katalog aplikasi lama diimpor",
  "pengaturan_operator.ubah": "Pengaturan Operator diubah",
  "akun.push_aktifkan": "Perangkat Push diaktifkan",
  "akun.push_matikan": "Perangkat Push dimatikan",
  "akun.email_verifikasi": "Verifikasi Email",
  "lokasi.buat": "Lokasi Mitra dibuat",
  "lokasi.ubah_profil": "Profil diubah",
  "lokasi.tandai_data_contoh": "Ditandai data contoh",
  "lokasi.ubah_dokumen": "Daftar dokumen diubah",
  "lokasi.ubah_kebijakan": "Kebijakan diubah",
  "lokasi.ubah_rekening": "Rekening diubah",
  "lokasi.unggah_perjanjian": "Scan perjanjian diunggah",
  "tarif.ubah_global": "Tarif global diubah",
  "tarif.buat_jenis_makam": "Jenis Makam ditambahkan",
  "tarif.ubah_jenis_makam": "Tarif Jenis Makam diubah",
  "tarif.ubah_biaya_pemakaman": "Biaya Pemakaman diubah",
  "tarif.tandai_diperiksa": "Tarif ditandai sudah diperiksa",
  "tarif.ubah_harga_layanan": "Harga Layanan diubah",
  "tarif.ubah_harga_layanan_dki": "Harga Layanan di TPU DKI diubah",
  "tarif.ubah_tarif_mitra_jasa": "Tarif Mitra Jasa diubah",
  "layanan.buat": "Layanan ditambahkan ke katalog",
  "layanan.ubah": "Layanan diubah",
  "layanan.hapus": "Layanan dihapus dari katalog",
  "layanan.tambah_varian": "Pilihan Layanan ditambahkan",
  "layanan.hapus_varian": "Pilihan Layanan dihapus",
  "layanan.tandai_tpu_dki": "Tanda boleh di TPU DKI diubah",
  "layanan.tawarkan": "Layanan ditawarkan di Lokasi ini",
  "layanan.stop_tawarkan": "Penawaran Layanan dihentikan",
  "paket_layanan.buat": "Paket Layanan ditambahkan",
  "paket_layanan.ubah": "Paket Layanan diubah",
  "paket_layanan.hapus": "Paket Layanan dihapus",
  "lokasi.ubah_jam_operasional": "Jam Operasional diubah",
  "lokasi.pilih_kontak_siaga": "Kontak Siaga dipilih",
  "hari_libur.tambah": "Hari Libur Nasional ditambahkan",
  "hari_libur.hapus": "Hari Libur Nasional dihapus",
  "tpu.buat": "TPU ditambahkan",
  "tpu.ubah": "Profil TPU diubah",
  "tpu.ubah_flag": "Status makam baru TPU diperiksa",
  "catatan_internal.tulis": "Catatan Internal",
  "antrean.ambil": "Baris Antrean diambil",
  "telepon_pemesan.catat_panggilan": "Panggilan Pemesan dicatat",
  "denah.buat_blok": "Blok dibuat",
  "denah.ubah_jenis_sel": "Jenis sel diubah",
  "denah.atur_jenis_makam": "Jenis Makam diatur",
  "denah.ubah_nomor": "Nomor Makam diubah",
  "denah.buat_kavling": "Kavling Keluarga dibuat",
  "denah.pisahkan_kavling": "Kavling Keluarga dipisahkan",
  "denah.ubah_baris_kolom": "Baris/kolom Blok diubah",
  "denah.unggah_foto_blok": "Foto denah Blok diunggah",
  "denah.bersihkan_petak": "Petak dibersihkan",
  "petak.nomor_ulang": "Nomor Petak diubah (renumbering)",
  "tugas_lapangan.buat": "Tugas Lapangan dibuat",
  "tugas_lapangan.selesai": "Tugas Lapangan ditandai Selesai",
  "lokasi.catat_kunjungan_verifikasi": "Kunjungan Verifikasi dicatat",
  "lokasi.catat_cek_denah": "Cek Denah dicatat",
  "lokasi.terbitkan": "Lokasi Mitra diterbitkan (Terverifikasi)",
  "lokasi.aktifkan_terencana": "Pemesanan Terencana diaktifkan",
  "denah.pakai_petak": "Petak dipakai untuk pesanan",
  "pemesanan.konfirmasi_saat_duka": "Pesanan Saat Duka dikonfirmasi",
  "pemesanan.centang_dokumen": "Dokumen ditandai sudah ada",
  "pencairan.tahan": "Pencairan ditahan",
  "pencairan.override_jumlah": "Jumlah Pencairan diubah",
  "pencairan.terbitkan_bukti": "Bukti Pencairan diterbitkan",
  "pencairan.catat_potongan": "Potongan dicatat",
  "pencairan.catat_potongan_lunas": "Potongan lunas dicatat",
  "pemesanan.tolak": "Pesanan Saat Duka ditolak",
  "pemesanan.tawarkan_alternatif": "Alternatif ditawarkan",
  "pemesanan.batalkan_untuk_pemesan": "Pembatalan dicatat untuk keluarga",
  "pemakaman.catat": "Pemakaman dicatat",
  "pemesanan.catat_pemakaman": "Pemakaman pesanan dicatat",
  "tagihan.catat_pembayaran_manual": "Pembayaran manual dicatat",
  "tagihan.catat_pembayaran_langsung": "Pembayaran langsung ke Lokasi Mitra dicatat",
  "tagihan.batalkan_pembayaran_langsung": "Pembayaran langsung dibatalkan",
  "tagihan.tetapkan_harga_khusus": "Harga Khusus ditetapkan",
  "lokasi.konfirmasi_syarat_tayang": "Syarat tayang dikonfirmasi masih terpenuhi",
  "pengurusan.konfirmasi_saat_duka_tpu": "Pengurusan Saat Duka di TPU dikonfirmasi",
  "pengurusan.tawarkan_tpu_lain": "TPU lain ditawarkan",
  "setor_retribusi.catat": "Setor Retribusi dicatat",
  "pengembalian.ajukan_goodwill": "Pengembalian dana goodwill diajukan",
  "pengembalian.setujui": "Pengembalian dana disetujui",
  "pengembalian.isi_rekening": "Rekening pengembalian dana dicatat",
  "pengembalian.isi_rekening_pemesan": "Rekening pengembalian dana diisi Pemesan",
  "pengembalian.terbitkan_bukti": "Bukti Pengembalian Dana diterbitkan",
  "hak_pakai.akhiri_tidak_tertagih": "Hak Pakai diakhiri (Tagihan Tidak Tertagih)",
  "tagihan.tidak_tertagih": "Tagihan dinyatakan Tidak Tertagih",
  "tagihan.catatan_ditambah": "Catatan ditambahkan pada Tagihan",
  "hak_pakai.selesaikan_verifikasi": "Hak Pakai dilengkapi (Perlu Verifikasi selesai)",
  "layanan.mulai_pekerjaan": "Pekerjaan Layanan dimulai",
  "layanan.unggah_bukti": "Bukti Pekerjaan Layanan diambil",
  "layanan.selesaikan_pekerjaan": "Pekerjaan Layanan diselesaikan",
};

/** The role an Entri Audit's actor wrote under. */
export function auditActorLabel(role: AuditActorRole): string {
  if (role === "seed_cli" || role === "ops_cli") return "Operator (server)";
  if (role === "pemesan") return "Pemilik Akun";
  return staffRoleLabels[role];
}
